// Code generated by scripts/generate-go-sdk.mjs. DO NOT EDIT.

package tokportal

const BaseURL = "https://app.tokportal.com/api/ext"

type Platform string

const (
	PlatformTiktok    Platform = "tiktok"
	PlatformInstagram Platform = "instagram"
)

type BundleType string

const (
	BundleTypeAccountOnly      BundleType = "account_only"
	BundleTypeAccountAndVideos BundleType = "account_and_videos"
	BundleTypeVideosOnly       BundleType = "videos_only"
)

type CreateBundleRequest struct {
	BundleType                BundleType `json:"bundle_type"`
	Platform                  Platform   `json:"platform,omitempty"`
	Country                   string     `json:"country,omitempty"`
	Title                     string     `json:"title,omitempty"`
	VideosQuantity            int        `json:"videos_quantity,omitempty"`
	EditsQuantity             int        `json:"edits_quantity,omitempty"`
	WantsNicheWarming         bool       `json:"wants_niche_warming,omitempty"`
	WantsDeepWarming          bool       `json:"wants_deep_warming,omitempty"`
	WantsAdvancedWarming      bool       `json:"wants_advanced_warming,omitempty"`
	AdvancedWarmingTerms      []string   `json:"advanced_warming_terms,omitempty"`
	AdvancedWarmingTermsCount int        `json:"advanced_warming_terms_count,omitempty"`
	NicheWarmingInstructions  string     `json:"niche_warming_instructions,omitempty"`
	AutoFinalizeVideos        bool       `json:"auto_finalize_videos,omitempty"`
	AccountId                 string     `json:"account_id,omitempty"`
	ExternalRef               string     `json:"external_ref,omitempty"`
}

type PatchBundleRequest struct {
	AutoFinalizeVideos bool    `json:"auto_finalize_videos,omitempty"`
	ExternalRef        *string `json:"external_ref,omitempty"`
	Title              *string `json:"title,omitempty"`
}

type CreateBulkBundlesRequest struct {
	Platforms                 []Platform `json:"platforms"`
	Country                   string     `json:"country"`
	AccountsCount             int        `json:"accounts_count"`
	UploadAccountsCount       int        `json:"upload_accounts_count,omitempty"`
	VideosPerAccount          int        `json:"videos_per_account,omitempty"`
	WantsNicheWarming         bool       `json:"wants_niche_warming,omitempty"`
	WantsDeepWarming          bool       `json:"wants_deep_warming,omitempty"`
	WantsAdvancedWarming      bool       `json:"wants_advanced_warming,omitempty"`
	AdvancedWarmingTerms      []string   `json:"advanced_warming_terms,omitempty"`
	AdvancedWarmingTermsCount int        `json:"advanced_warming_terms_count,omitempty"`
	NicheWarmingInstructions  string     `json:"niche_warming_instructions,omitempty"`
	AutoFinalizeVideos        bool       `json:"auto_finalize_videos,omitempty"`
	ExternalRef               string     `json:"external_ref,omitempty"`
}

type ConfigureAccountRequest struct {
	Username                 string   `json:"username"`
	VisibleName              string   `json:"visible_name"`
	Biography                string   `json:"biography,omitempty"`
	ProfilePictureUrl        string   `json:"profile_picture_url,omitempty"`
	LinkInBio                string   `json:"link_in_bio,omitempty"`
	NicheWarmingInstructions string   `json:"niche_warming_instructions,omitempty"`
	AdvancedWarmingTerms     []string `json:"advanced_warming_terms,omitempty"`
}

type ConfigureVideoRequest struct {
	VideoType              string   `json:"video_type"`
	Description            string   `json:"description,omitempty"`
	TargetPublishDate      string   `json:"target_publish_date"`
	Name                   string   `json:"name,omitempty"`
	VideoUrl               string   `json:"video_url,omitempty"`
	CarouselImages         []string `json:"carousel_images,omitempty"`
	CarouselTitle          string   `json:"carousel_title,omitempty"`
	StoryImageUrl          string   `json:"story_image_url,omitempty"`
	StoryRepostUrl         string   `json:"story_repost_url,omitempty"`
	TiktokSoundUrl         string   `json:"tiktok_sound_url,omitempty"`
	VolumeOriginalSound    *int     `json:"volume_original_sound,omitempty"`
	VolumeAddedSound       *int     `json:"volume_added_sound,omitempty"`
	EditingInstructions    string   `json:"editing_instructions,omitempty"`
	ExternalRef            string   `json:"external_ref,omitempty"`
	InstagramContentType   string   `json:"instagram_content_type,omitempty"`
	InstagramLocation      string   `json:"instagram_location,omitempty"`
	InstagramCollaborators []string `json:"instagram_collaborators,omitempty"`
	InstagramAudioName     string   `json:"instagram_audio_name,omitempty"`
	InstagramAddToStory    bool     `json:"instagram_add_to_story,omitempty"`
	AiContentDisclaimer    bool     `json:"ai_content_disclaimer,omitempty"`
	DiscloseAsAds          bool     `json:"disclose_as_ads,omitempty"`
	InstantRepostAsStory   bool     `json:"instant_repost_as_story,omitempty"`
	YoutubeTitle           string   `json:"youtube_title,omitempty"`
	YoutubeTags            []string `json:"youtube_tags,omitempty"`
	YoutubeCategory        string   `json:"youtube_category,omitempty"`
	YoutubeVisibility      string   `json:"youtube_visibility,omitempty"`
	YoutubeSoundUrl        string   `json:"youtube_sound_url,omitempty"`
	AutoPublish            bool     `json:"auto_publish,omitempty"`
}

type PatchVideoRequest struct {
	ExternalRef            *string `json:"external_ref,omitempty"`
	Name                   *string `json:"name,omitempty"`
	Description            *string `json:"description,omitempty"`
	TargetPublishDate      *string `json:"target_publish_date,omitempty"`
	TargetPublishStartDate *string `json:"target_publish_start_date,omitempty"`
	TargetPublishEndDate   *string `json:"target_publish_end_date,omitempty"`
}

type QuantityRequest struct {
	Quantity int `json:"quantity"`
}

type AccountEditRequest struct {
	RequestedUsername          string `json:"requested_username"`
	RequestedVisibleName       string `json:"requested_visible_name"`
	RequestedBiography         string `json:"requested_biography,omitempty"`
	RequestedProfilePictureUrl string `json:"requested_profile_picture_url,omitempty"`
	RequestedLinkInBio         string `json:"requested_link_in_bio,omitempty"`
}

type DisputeCommentRequest struct {
	Reason string `json:"reason"`
}

type CreateWebhookEndpointRequest struct {
	Url         string   `json:"url"`
	Events      []string `json:"events"`
	Description string   `json:"description,omitempty"`
	Enabled     bool     `json:"enabled,omitempty"`
}

type UpdateWebhookEndpointRequest struct {
	Url         string   `json:"url,omitempty"`
	Events      []string `json:"events,omitempty"`
	Description *string  `json:"description,omitempty"`
	Enabled     bool     `json:"enabled,omitempty"`
}

type UploadVideoRequest struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type,omitempty"`
	BundleId    string `json:"bundle_id"`
}

type UploadImageRequest struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	BundleId    string `json:"bundle_id"`
	Purpose     string `json:"purpose,omitempty"`
}

type UploadImageFromUrlRequest struct {
	Url      string `json:"url"`
	BundleId string `json:"bundle_id"`
	Purpose  string `json:"purpose,omitempty"`
}

type CreateAnalyticsReportRequest struct {
	Title       *string    `json:"title,omitempty"`
	Template    *string    `json:"template,omitempty"`
	BrandName   *string    `json:"brandName,omitempty"`
	BrandAccent *string    `json:"brandAccent,omitempty"`
	AccountIds  []string   `json:"accountIds,omitempty"`
	WorkspaceId *string    `json:"workspaceId,omitempty"`
	Platforms   []Platform `json:"platforms,omitempty"`
	Countries   []string   `json:"countries,omitempty"`
	Query       *string    `json:"query,omitempty"`
	From        *string    `json:"from,omitempty"`
	To          *string    `json:"to,omitempty"`
}

type AccountCorrectionsRequest struct {
	Comment string         `json:"comment"`
	Fields  map[string]any `json:"fields,omitempty"`
}

type VideoCorrectionsRequest struct {
	Comment string         `json:"comment"`
	Fields  map[string]any `json:"fields,omitempty"`
}

type FixVideoDownloadRequest struct {
	VideoUrl       string   `json:"video_url,omitempty"`
	CarouselImages []string `json:"carousel_images,omitempty"`
}

type RefreshAnalyticsRequest struct {
	Force           bool `json:"force,omitempty"`
	IncludePosts    bool `json:"includePosts,omitempty"`
	IncludeComments bool `json:"includeComments,omitempty"`
	ForcePosts      bool `json:"forcePosts,omitempty"`
	BootstrapPosts  bool `json:"bootstrapPosts,omitempty"`
	PostLimit       int  `json:"postLimit,omitempty"`
}

type BatchConfigureVideoItem struct {
	Position int `json:"position"`
	ConfigureVideoRequest
}

type BatchConfigureVideosRequest struct {
	Videos      []BatchConfigureVideoItem `json:"videos"`
	AutoPublish bool                      `json:"auto_publish,omitempty"`
}

type CommentTaskInput struct {
	SavedAccountID string  `json:"saved_account_id"`
	TargetVideoURL string  `json:"target_video_url"`
	CommentText    string  `json:"comment_text"`
	BriefID        *string `json:"brief_id,omitempty"`
}

type CreateCommentTasksRequest struct {
	SavedAccountID string             `json:"saved_account_id,omitempty"`
	TargetVideoURL string             `json:"target_video_url,omitempty"`
	CommentText    string             `json:"comment_text,omitempty"`
	BriefID        *string            `json:"brief_id,omitempty"`
	Tasks          []CommentTaskInput `json:"tasks,omitempty"`
}

var OperationIDs = []string{
	"getCurrentUser",
	"updateCurrentUserSettings",
	"getAccountManagedSubscription",
	"reactivateAccountManagedSubscription",
	"cancelAccountManagedSubscription",
	"listCountries",
	"listPlatforms",
	"getCreditCosts",
	"getCreditBalance",
	"listCreditTransactions",
	"listBundles",
	"createBundle",
	"createBundlesBulk",
	"getBundle",
	"updateBundle",
	"publishBundle",
	"getBundlePublishReadiness",
	"unpublishBundle",
	"addVideoSlots",
	"addEditSlots",
	"getBundleAccount",
	"configureBundleAccount",
	"requestBundleAccountCorrections",
	"finalizeBundleAccount",
	"listBundleVideos",
	"getBundleVideo",
	"configureBundleVideo",
	"patchBundleVideo",
	"batchConfigureBundleVideos",
	"publishAllBundleVideos",
	"importBundleVideosCsv",
	"publishBundleVideo",
	"resetBundleVideo",
	"unscheduleBundleVideo",
	"finalizeBundleVideo",
	"requestBundleVideoCorrections",
	"fixBundleVideoDownload",
	"listAccounts",
	"listAccountBans",
	"getAccount",
	"updateAccountCommentingProfile",
	"listAccountBundles",
	"retrieveAccountVerificationCode",
	"revealAccountCredentials",
	"canRefreshAccountAnalytics",
	"refreshAccountAnalytics",
	"getAccountEditRequest",
	"createAccountEditRequest",
	"rewarmAccount",
	"configureBundleWarmingTerms",
	"listAccountWarmingSessions",
	"getWarmingSession",
	"generateWarmingTerms",
	"listWebhookEvents",
	"listWebhookEndpoints",
	"createWebhookEndpoint",
	"getWebhookEndpoint",
	"updateWebhookEndpoint",
	"deleteWebhookEndpoint",
	"listWebhookDeliveries",
	"retryWebhookDelivery",
	"testWebhookEndpoint",
	"uploadVideo",
	"uploadVideoDirect",
	"uploadImage",
	"uploadImageDirect",
	"uploadImageFromUrl",
	"getAnalyticsDashboard",
	"getAnalyticsContract",
	"exportAnalyticsVideos",
	"createAnalyticsReport",
	"exportAnalyticsReportHtml",
	"getAnalyticsSeries",
	"getAnalyticsAccount",
	"refreshAnalyticsAccount",
	"listAnalyticsAccountRawSnapshots",
	"getAccountAnalytics",
	"listAccountVideoAnalytics",
	"getVideoAnalytics",
	"createVideoAdCodeRequest",
	"getVideoAdCodeRequest",
	"getCommentPulse",
	"listAnalyticsAccountComments",
	"listAnalyticsPostRawSnapshots",
	"listCommentTasks",
	"createCommentTasks",
	"getCommentTask",
	"deleteCommentTask",
	"approveCommentTask",
	"disputeCommentTask",
	"listCommentTaskVerifications",
}

type OperationDefinition struct {
	OperationID         string
	Method              string
	Path                string
	IdempotencyPolicy   string
	PathParams          []string
	QueryParams         []string
	HasJSONBody         bool
	RequestContentType  string
	SuccessContentTypes []string
}

var OperationDefinitions = map[string]OperationDefinition{
	"getCurrentUser": {
		OperationID:         "getCurrentUser",
		Method:              "GET",
		Path:                "/me",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"updateCurrentUserSettings": {
		OperationID:         "updateCurrentUserSettings",
		Method:              "PATCH",
		Path:                "/me",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getAccountManagedSubscription": {
		OperationID:         "getAccountManagedSubscription",
		Method:              "GET",
		Path:                "/accounts/{id}/managed-subscription",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"reactivateAccountManagedSubscription": {
		OperationID:         "reactivateAccountManagedSubscription",
		Method:              "POST",
		Path:                "/accounts/{id}/managed-subscription/reactivate",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"cancelAccountManagedSubscription": {
		OperationID:         "cancelAccountManagedSubscription",
		Method:              "POST",
		Path:                "/accounts/{id}/managed-subscription/cancel",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listCountries": {
		OperationID:         "listCountries",
		Method:              "GET",
		Path:                "/countries",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listPlatforms": {
		OperationID:         "listPlatforms",
		Method:              "GET",
		Path:                "/platforms",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getCreditCosts": {
		OperationID:         "getCreditCosts",
		Method:              "GET",
		Path:                "/credit-costs",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getCreditBalance": {
		OperationID:         "getCreditBalance",
		Method:              "GET",
		Path:                "/credits/balance",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listCreditTransactions": {
		OperationID:         "listCreditTransactions",
		Method:              "GET",
		Path:                "/credits/history",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"page", "per_page", "date_from", "date_to"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listBundles": {
		OperationID:         "listBundles",
		Method:              "GET",
		Path:                "/bundles",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"page", "per_page", "status", "bundle_type", "platform", "external_ref", "account_status"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"createBundle": {
		OperationID:         "createBundle",
		Method:              "POST",
		Path:                "/bundles",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"createBundlesBulk": {
		OperationID:         "createBundlesBulk",
		Method:              "POST",
		Path:                "/bundles/bulk",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getBundle": {
		OperationID:         "getBundle",
		Method:              "GET",
		Path:                "/bundles/{id}",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"updateBundle": {
		OperationID:         "updateBundle",
		Method:              "PATCH",
		Path:                "/bundles/{id}",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"publishBundle": {
		OperationID:         "publishBundle",
		Method:              "POST",
		Path:                "/bundles/{id}/publish",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getBundlePublishReadiness": {
		OperationID:         "getBundlePublishReadiness",
		Method:              "GET",
		Path:                "/bundles/{id}/publish-readiness",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"unpublishBundle": {
		OperationID:         "unpublishBundle",
		Method:              "POST",
		Path:                "/bundles/{id}/unpublish",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"addVideoSlots": {
		OperationID:         "addVideoSlots",
		Method:              "POST",
		Path:                "/bundles/{id}/add-video-slots",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"addEditSlots": {
		OperationID:         "addEditSlots",
		Method:              "POST",
		Path:                "/bundles/{id}/add-edit-slots",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getBundleAccount": {
		OperationID:         "getBundleAccount",
		Method:              "GET",
		Path:                "/bundles/{id}/account",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"configureBundleAccount": {
		OperationID:         "configureBundleAccount",
		Method:              "PUT",
		Path:                "/bundles/{id}/account",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"requestBundleAccountCorrections": {
		OperationID:         "requestBundleAccountCorrections",
		Method:              "POST",
		Path:                "/bundles/{id}/account/corrections",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"finalizeBundleAccount": {
		OperationID:         "finalizeBundleAccount",
		Method:              "POST",
		Path:                "/bundles/{id}/account/finalize",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listBundleVideos": {
		OperationID:         "listBundleVideos",
		Method:              "GET",
		Path:                "/bundles/{id}/videos",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getBundleVideo": {
		OperationID:         "getBundleVideo",
		Method:              "GET",
		Path:                "/bundles/{id}/videos/{position}",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"configureBundleVideo": {
		OperationID:         "configureBundleVideo",
		Method:              "PUT",
		Path:                "/bundles/{id}/videos/{position}",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"patchBundleVideo": {
		OperationID:         "patchBundleVideo",
		Method:              "PATCH",
		Path:                "/bundles/{id}/videos/{position}",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"batchConfigureBundleVideos": {
		OperationID:         "batchConfigureBundleVideos",
		Method:              "PUT",
		Path:                "/bundles/{id}/videos/batch",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"publishAllBundleVideos": {
		OperationID:         "publishAllBundleVideos",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/publish-all",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"importBundleVideosCsv": {
		OperationID:         "importBundleVideosCsv",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/import-csv",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "multipart/form-data",
		SuccessContentTypes: []string{"application/json"},
	},
	"publishBundleVideo": {
		OperationID:         "publishBundleVideo",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/{position}/publish",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"resetBundleVideo": {
		OperationID:         "resetBundleVideo",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/{position}/reset",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"unscheduleBundleVideo": {
		OperationID:         "unscheduleBundleVideo",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/{position}/unschedule",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"finalizeBundleVideo": {
		OperationID:         "finalizeBundleVideo",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/{position}/finalize",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"requestBundleVideoCorrections": {
		OperationID:         "requestBundleVideoCorrections",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/{position}/corrections",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"fixBundleVideoDownload": {
		OperationID:         "fixBundleVideoDownload",
		Method:              "POST",
		Path:                "/bundles/{id}/videos/{position}/fix-download",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "position"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAccounts": {
		OperationID:         "listAccounts",
		Method:              "GET",
		Path:                "/accounts",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"page", "per_page", "platform", "country", "banned"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAccountBans": {
		OperationID:         "listAccountBans",
		Method:              "GET",
		Path:                "/account-bans",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"page", "per_page", "status", "resolution", "account_id", "since", "include_screenshots"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getAccount": {
		OperationID:         "getAccount",
		Method:              "GET",
		Path:                "/accounts/{id}",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"updateAccountCommentingProfile": {
		OperationID:         "updateAccountCommentingProfile",
		Method:              "PATCH",
		Path:                "/accounts/{id}/commenting-profile",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAccountBundles": {
		OperationID:         "listAccountBundles",
		Method:              "GET",
		Path:                "/accounts/{id}/bundles",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{"page", "per_page", "status"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"retrieveAccountVerificationCode": {
		OperationID:         "retrieveAccountVerificationCode",
		Method:              "POST",
		Path:                "/accounts/{id}/verification-code",
		IdempotencyPolicy:   "reject-sensitive-response",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"revealAccountCredentials": {
		OperationID:         "revealAccountCredentials",
		Method:              "POST",
		Path:                "/accounts/{id}/reveal-credentials",
		IdempotencyPolicy:   "reject-sensitive-response",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"canRefreshAccountAnalytics": {
		OperationID:         "canRefreshAccountAnalytics",
		Method:              "GET",
		Path:                "/accounts/{id}/analytics/can-refresh",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"refreshAccountAnalytics": {
		OperationID:         "refreshAccountAnalytics",
		Method:              "POST",
		Path:                "/accounts/{id}/analytics/refresh",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getAccountEditRequest": {
		OperationID:         "getAccountEditRequest",
		Method:              "GET",
		Path:                "/accounts/{id}/edit-request",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"createAccountEditRequest": {
		OperationID:         "createAccountEditRequest",
		Method:              "POST",
		Path:                "/accounts/{id}/edit-request",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"rewarmAccount": {
		OperationID:         "rewarmAccount",
		Method:              "POST",
		Path:                "/accounts/{id}/rewarm",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"configureBundleWarmingTerms": {
		OperationID:         "configureBundleWarmingTerms",
		Method:              "PUT",
		Path:                "/bundles/{id}/warming-terms",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAccountWarmingSessions": {
		OperationID:         "listAccountWarmingSessions",
		Method:              "GET",
		Path:                "/accounts/{id}/warming-sessions",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getWarmingSession": {
		OperationID:         "getWarmingSession",
		Method:              "GET",
		Path:                "/warming-sessions/{id}",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"generateWarmingTerms": {
		OperationID:         "generateWarmingTerms",
		Method:              "POST",
		Path:                "/warming/generate-terms",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"listWebhookEvents": {
		OperationID:         "listWebhookEvents",
		Method:              "GET",
		Path:                "/webhooks/events",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listWebhookEndpoints": {
		OperationID:         "listWebhookEndpoints",
		Method:              "GET",
		Path:                "/webhooks",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"page", "per_page", "enabled", "event"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"createWebhookEndpoint": {
		OperationID:         "createWebhookEndpoint",
		Method:              "POST",
		Path:                "/webhooks",
		IdempotencyPolicy:   "reject-sensitive-response",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getWebhookEndpoint": {
		OperationID:         "getWebhookEndpoint",
		Method:              "GET",
		Path:                "/webhooks/{id}",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"updateWebhookEndpoint": {
		OperationID:         "updateWebhookEndpoint",
		Method:              "PATCH",
		Path:                "/webhooks/{id}",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"deleteWebhookEndpoint": {
		OperationID:         "deleteWebhookEndpoint",
		Method:              "DELETE",
		Path:                "/webhooks/{id}",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{},
	},
	"listWebhookDeliveries": {
		OperationID:         "listWebhookDeliveries",
		Method:              "GET",
		Path:                "/webhooks/{id}/deliveries",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{"page", "per_page", "event_type", "success"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"retryWebhookDelivery": {
		OperationID:         "retryWebhookDelivery",
		Method:              "POST",
		Path:                "/webhooks/{id}/deliveries/{delivery_id}/retry",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id", "delivery_id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"testWebhookEndpoint": {
		OperationID:         "testWebhookEndpoint",
		Method:              "POST",
		Path:                "/webhooks/{id}/test",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"uploadVideo": {
		OperationID:         "uploadVideo",
		Method:              "POST",
		Path:                "/upload/video",
		IdempotencyPolicy:   "reject-sensitive-response",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"uploadVideoDirect": {
		OperationID:         "uploadVideoDirect",
		Method:              "POST",
		Path:                "/upload/video/direct",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "multipart/form-data",
		SuccessContentTypes: []string{"application/json"},
	},
	"uploadImage": {
		OperationID:         "uploadImage",
		Method:              "POST",
		Path:                "/upload/image",
		IdempotencyPolicy:   "reject-sensitive-response",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"uploadImageDirect": {
		OperationID:         "uploadImageDirect",
		Method:              "POST",
		Path:                "/upload/image/direct",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "multipart/form-data",
		SuccessContentTypes: []string{"application/json"},
	},
	"uploadImageFromUrl": {
		OperationID:         "uploadImageFromUrl",
		Method:              "POST",
		Path:                "/upload/image/from-url",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getAnalyticsDashboard": {
		OperationID:         "getAnalyticsDashboard",
		Method:              "GET",
		Path:                "/analytics",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"workspace", "platform", "country", "account", "from", "to"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getAnalyticsContract": {
		OperationID:         "getAnalyticsContract",
		Method:              "GET",
		Path:                "/analytics/contract",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"exportAnalyticsVideos": {
		OperationID:         "exportAnalyticsVideos",
		Method:              "GET",
		Path:                "/analytics/export/videos",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"account", "workspace", "platform", "country", "q", "from", "to"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"text/csv"},
	},
	"createAnalyticsReport": {
		OperationID:         "createAnalyticsReport",
		Method:              "POST",
		Path:                "/analytics/export/reports",
		IdempotencyPolicy:   "reject-sensitive-response",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"exportAnalyticsReportHtml": {
		OperationID:         "exportAnalyticsReportHtml",
		Method:              "POST",
		Path:                "/analytics/export/reports/html",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"text/html"},
	},
	"getAnalyticsSeries": {
		OperationID:         "getAnalyticsSeries",
		Method:              "GET",
		Path:                "/analytics/series",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"metric", "granularity", "mode", "account", "from", "to"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getAnalyticsAccount": {
		OperationID:         "getAnalyticsAccount",
		Method:              "GET",
		Path:                "/analytics/accounts/{id}",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"refreshAnalyticsAccount": {
		OperationID:         "refreshAnalyticsAccount",
		Method:              "POST",
		Path:                "/analytics/accounts/{id}/refresh",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAnalyticsAccountRawSnapshots": {
		OperationID:         "listAnalyticsAccountRawSnapshots",
		Method:              "GET",
		Path:                "/analytics/accounts/{id}/raw",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{"source", "limit", "from", "to"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getAccountAnalytics": {
		OperationID:         "getAccountAnalytics",
		Method:              "GET",
		Path:                "/accounts/{id}/analytics",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAccountVideoAnalytics": {
		OperationID:         "listAccountVideoAnalytics",
		Method:              "GET",
		Path:                "/accounts/{id}/analytics/videos",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{"page", "per_page", "sort_by", "sort_order"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getVideoAnalytics": {
		OperationID:         "getVideoAnalytics",
		Method:              "GET",
		Path:                "/videos/{id}/analytics",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"createVideoAdCodeRequest": {
		OperationID:         "createVideoAdCodeRequest",
		Method:              "POST",
		Path:                "/videos/{id}/ad-code-request",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getVideoAdCodeRequest": {
		OperationID:         "getVideoAdCodeRequest",
		Method:              "GET",
		Path:                "/videos/{id}/ad-code-request",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"getCommentPulse": {
		OperationID:         "getCommentPulse",
		Method:              "GET",
		Path:                "/analytics/comments",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"platform", "country", "account", "post", "limit", "postLimit", "from", "to"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAnalyticsAccountComments": {
		OperationID:         "listAnalyticsAccountComments",
		Method:              "GET",
		Path:                "/analytics/accounts/{id}/comments",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{"trackedPostId", "postId", "limit"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listAnalyticsPostRawSnapshots": {
		OperationID:         "listAnalyticsPostRawSnapshots",
		Method:              "GET",
		Path:                "/analytics/posts/{id}/raw",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{"source", "limit", "from", "to"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"listCommentTasks": {
		OperationID:         "listCommentTasks",
		Method:              "GET",
		Path:                "/comments",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{},
		QueryParams:         []string{"page", "per_page", "status", "saved_account_id"},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"createCommentTasks": {
		OperationID:         "createCommentTasks",
		Method:              "POST",
		Path:                "/comments",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"getCommentTask": {
		OperationID:         "getCommentTask",
		Method:              "GET",
		Path:                "/comments/{id}",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"deleteCommentTask": {
		OperationID:         "deleteCommentTask",
		Method:              "DELETE",
		Path:                "/comments/{id}",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"approveCommentTask": {
		OperationID:         "approveCommentTask",
		Method:              "POST",
		Path:                "/comments/{id}/approve",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
	"disputeCommentTask": {
		OperationID:         "disputeCommentTask",
		Method:              "POST",
		Path:                "/comments/{id}/dispute",
		IdempotencyPolicy:   "standard",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         true,
		RequestContentType:  "application/json",
		SuccessContentTypes: []string{"application/json"},
	},
	"listCommentTaskVerifications": {
		OperationID:         "listCommentTaskVerifications",
		Method:              "GET",
		Path:                "/comments/{id}/verifications",
		IdempotencyPolicy:   "not-applicable",
		PathParams:          []string{"id"},
		QueryParams:         []string{},
		HasJSONBody:         false,
		RequestContentType:  "",
		SuccessContentTypes: []string{"application/json"},
	},
}
